"use client";
import {useEffect,useState} from 'react';
import {createPortal} from 'react-dom';
import type {Chat,Post} from '@/lib/types';
import {encryptMessage,type PublicDevice} from '@/lib/crypto-chat';
import {api,errorText,Avatar} from './shared';
import {registerDevice} from './preferences';
import {loadAttachment,uploadFiles,MediaList,type Attachment} from './media';
export type ShareContent={body:string;attachments:Attachment[]};
export async function recipientDevices(chatId:string,userId:string){await registerDevice(userId);const devices=await api<PublicDevice[]>('chats/'+chatId+'/keys');const pin='telejka-peers:'+userId+':'+chatId,value=devices.map(d=>d.id+':'+d.public_key.n).sort().join('|'),previous=localStorage.getItem(pin);if(previous&&previous!==value&&!window.confirm('У участника изменились устройства. Продолжить отправку?'))throw Error('Отправка отменена.');localStorage.setItem(pin,value);return devices;}
export function ShareButton({userId,author,content,resolveContent}:{userId:string;author:string;content:ShareContent;resolveContent?:()=>Promise<ShareContent>}){
 const [open,setOpen]=useState(false),[chats,setChats]=useState<Chat[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[query,setQuery]=useState(''),[sent,setSent]=useState(false);
 async function show(){setOpen(true);setSent(false);setError('');try{setChats(await api<Chat[]>('chats'))}catch(e){setError(errorText(e))}}
 async function send(chat:Chat){setBusy(true);setError('');try{const resolved=resolveContent?await resolveContent():content;const devices=await recipientDevices(chat.id,userId);const files:File[]=[];for(const item of resolved.attachments){const blob=await loadAttachment(item);files.push(new File([blob],item.name,{type:item.mime}))}const attachments=await uploadFiles(files,chat.id);const envelope=await encryptMessage(chat.id,{body:'Переслано от '+author+'\n'+resolved.body,attachments},devices);await api('chats/'+chat.id+'/messages','POST',{envelope,clientId:crypto.randomUUID(),attachmentIds:attachments.map(a=>a.id)});setOpen(false);setSent(true)}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 return <><button type="button" onClick={()=>void show()}>{sent?'Отправлено ✓':'Переслать'}</button>{open&&createPortal(<div className="modal-backdrop"><section className="modal share-dialog" role="dialog" aria-modal="true" aria-label="Переслать в чат"><header><h2>Переслать в чат</h2><button disabled={busy} onClick={()=>setOpen(false)} aria-label="Закрыть">×</button></header><input aria-label="Найти чат" placeholder="Найти чат" value={query} onChange={e=>setQuery(e.target.value)}/>{error&&<p role="alert">{error}</p>}{busy&&<p role="status">Шифруем и отправляем…</p>}{chats.filter(chat=>(chat.title||chat.participants.filter(p=>p.id!==userId).map(p=>p.name).join(', ')).toLowerCase().includes(query.toLowerCase())).map(chat=>{const person=chat.participants.find(p=>p.id!==userId)||chat.participants[0];return <button key={chat.id} disabled={busy} onClick={()=>void send(chat)}>{person&&<Avatar user={person} size={32}/>}<span>{chat.title||person?.name||'Чат'}</span></button>})}{!chats.length&&<p>Сначала создай чат в разделе «Сообщения».</p>}</section></div>,document.body)}</>;
}
export function EditContent({body,onSave}:{body:string;onSave:(body:string)=>Promise<void>}){const [editing,setEditing]=useState(false),[value,setValue]=useState(body),[busy,setBusy]=useState(false),[error,setError]=useState('');return <><button type="button" onClick={()=>{setValue(body);setEditing(true)}}>Редактировать</button>{editing&&createPortal(<div className="modal-backdrop"><form className="modal edit-content" role="dialog" aria-modal="true" aria-label="Редактирование" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await onSave(value);setEditing(false)}catch(err){setError(errorText(err))}finally{setBusy(false)}}}><h2>Редактирование</h2><textarea aria-label="Текст" value={value} maxLength={5000} onChange={e=>setValue(e.target.value)}/>{error&&<p role="alert">{error}</p>}<div className="content-tools"><button disabled={busy}>Сохранить</button><button type="button" disabled={busy} onClick={()=>setEditing(false)}>Отмена</button></div></form></div>,document.body)}</>}
export function RepostCard({id}:{id?:string|null}){const [post,setPost]=useState<Post|null>(null);useEffect(()=>{let live=true;if(id)void api<Post>('posts/'+id).then(async p=>{if(p.poll_id){const poll=await api<{payload:{question:string;options:string[]}}>('polls/'+p.poll_id);p={...p,body:poll.payload.question+'\n'+poll.payload.options.join('\n')}}if(live)setPost(p)}).catch(()=>{});return()=>{live=false}},[id]);return <section className="repost-card">{post?<><small>↻ Репост · {post.author.name}</small><p>{post.body}</p><MediaList items={post.attachments}/></>:<p>Исходная публикация недоступна.</p>}</section>}
export function PostTools({post,userId,onChange}:{post:Post;userId:string;onChange:()=>void}){const [error,setError]=useState(''),[busy,setBusy]=useState(false);return <><div className="content-tools">{post.author.id===userId&&!post.poll_id&&<EditContent body={post.body} onSave={async body=>{await api('posts/'+post.id,'PATCH',{body});onChange()}}/>}<button disabled={busy} onClick={async()=>{setBusy(true);try{await api('posts/'+post.id+'/repost','POST',{});onChange()}catch(e){setError(errorText(e))}finally{setBusy(false)}}}>Репост</button><ShareButton userId={userId} author={post.author.name} resolveContent={async()=>{const source=post.repost_id?await api<Post>("posts/"+post.repost_id):post;if(source.poll_id){const poll=await api<{payload:{question:string;options:string[]}}>("polls/"+source.poll_id);return {body:poll.payload.question+"\n"+poll.payload.options.join("\n"),attachments:[]}}return {body:source.body,attachments:source.attachments||[]}}} content={{body:post.body,attachments:post.attachments||[]}}/></div>{error&&<p role="alert">{error}</p>}</>}
