"use client";
import {useEffect,useState} from 'react';
import {api,errorText} from './shared';
function keyBytes(key:string){const bytes=atob(key.replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from(bytes,c=>c.charCodeAt(0));}
async function worker(){await navigator.serviceWorker.register('/sw.js',{scope:'/'});return navigator.serviceWorker.ready}
export function PushSettings({userId,compact=false}:{userId:string;compact?:boolean}){
 const [supported,setSupported]=useState(false),[enabled,setEnabled]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[ready,setReady]=useState(false),[denied,setDenied]=useState(false),[testResult,setTestResult]=useState('');
 useEffect(()=>{let active=true;const valid='serviceWorker' in navigator&&'PushManager' in window&&'Notification' in window;setSupported(valid);setReady(true);if(valid){setDenied(Notification.permission==='denied');worker().then(r=>r.pushManager.getSubscription()).then(async s=>{if(!s||Notification.permission!=='granted'){if(active)setEnabled(false);return}await api('push/subscription','POST',s.toJSON());const status=await api<{connected:boolean}>('push/status');if(active)setEnabled(status.connected)}).catch(e=>{if(active)setError(errorText(e))})}return()=>{active=false}},[userId]);
 async function enable(){setBusy(true);setError('');try{
  // The permission prompt is initiated directly by the user's button click.
  const permission=await Notification.requestPermission();setDenied(permission==='denied');if(permission!=='granted')throw Error('Разрешите уведомления в настройках сайта и устройства.');
  const r=await worker();const {publicKey}=await api<{publicKey:string}>('push/key');
  const subscription=await r.pushManager.getSubscription()||await r.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:keyBytes(publicKey)});
  await api('push/subscription','POST',subscription.toJSON());setEnabled(true);
 }catch(e){setError(errorText(e))}finally{setBusy(false)}}
 async function disable(){setBusy(true);setError('');try{await api('push/subscription','DELETE');const r=await worker();await (await r.pushManager.getSubscription())?.unsubscribe();setEnabled(false);}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 async function testPush(){setBusy(true);setError('');setTestResult('');try{await api('push/test','POST',{});setTestResult('Служба push приняла отправку. Если уведомления нет, проверь настройки ниже. Это ещё не подтверждение показа на телефоне.')}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 return <section className={compact?'push-compact':'section-pad'}><div className="settings-card push-settings"><h2>Уведомления на устройстве</h2><p>Разреши уведомления именно в установленной TELEJKA. Разрешение в Safari и в приложении может отличаться.</p>{ready&&supported?<><button className="secondary" disabled={busy} onClick={enabled?disable:enable}>{busy?'Подключаем…':enabled?'Отключить уведомления':'Включить уведомления'}</button>{enabled&&<button className="secondary" disabled={busy} onClick={testPush}>Проверить push</button>}<p className="muted small">{enabled?'Уведомления включены на этом устройстве.':denied?'Уведомления заблокированы. Разрешите их в настройках браузера.':'Браузер запросит разрешение после нажатия кнопки.'}</p></>:ready?<p>На iPhone: Safari → «Поделиться» → «На экран Домой». Открой TELEJKA с появившейся иконки. На других устройствах используй браузер с поддержкой push.</p>:<p>Проверка устройства…</p>}<details className="push-phone-help"><summary>Если уведомления не приходят</summary><p><strong>iPhone (iOS 16.4+):</strong> добавь сайт через Safari → «Поделиться» → «На экран Домой». Открой эту иконку, войди и нажми «Включить уведомления». Затем: Настройки iPhone → Уведомления → TELEJKA → Допуск уведомлений, Экран блокировки, Баннеры и Звуки. Проверь «Фокусирование» и «Сводку по расписанию».</p><p><strong>Android:</strong> разреши уведомления TELEJKA в браузере и уведомления браузера/приложения в настройках телефона. При задержках проверь ограничения фоновой работы и энергосбережение.</p><p><strong>Заблокированный экран:</strong> уведомления могут приходить. <strong>Телефон полностью выключен:</strong> доставка возможна только после включения и появления интернета. Push ожидает доставки до суток; сами сообщения остаются в чате.</p></details>{testResult&&<p role="status" className="muted small">{testResult}</p>}{error&&<p className="error" role="alert">{error}</p>}</div></section>
}
export function PushSync({userId}:{userId:string}){
 useEffect(()=>{if(!('serviceWorker' in navigator)||!('PushManager' in window)||!('Notification' in window)||Notification.permission!=='granted')return;let active=true;worker().then(r=>r.pushManager.getSubscription()).then(s=>{if(active&&s)return api('push/subscription','POST',s.toJSON())}).catch(()=>{});return()=>{active=false}},[userId]);return null;
}
