"use client";
import {useEffect,useState} from 'react';
import {api,UserName,errorText} from './shared';
import {registerDevice} from './preferences';
import {encryptMessage,decryptMessage,type PublicDevice,type Envelope} from '@/lib/crypto-chat';
import type {User} from '@/lib/types';
export function FollowControl({target,userId}:{target:string;userId:string}){
 const [stats,setStats]=useState<{followers:number;following:number;subscribed:boolean}>(),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let live=true;api<any>('follows/'+target).then(v=>{if(live)setStats(v)}).catch(e=>{if(live)setError(errorText(e))});return()=>{live=false}},[target]);
 return <div className="follow-control"><span>{stats?`${stats.followers} подписчиков · ${stats.following} подписок`:'Подписчики…'}</span>{target!==userId&&stats&&<button className="secondary" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{setStats(await api('follows/'+target,stats.subscribed?'DELETE':'POST'))}catch(e){setError(errorText(e))}finally{setBusy(false)}}}>{stats.subscribed?'Отписаться':'Подписаться'}</button>}{error&&<small role="alert">{error}</small>}</div>
}
type Content={question:string;options:string[]};
type Poll={id:string;payload:Content|Envelope;author:User;counts:Record<string,number>;choice:number|null;content?:Content};
export function Polls({user,chatId,authorId,readOnly=false}:{user:User;chatId?:string;authorId?:string;readOnly?:boolean}){
 const [polls,setPolls]=useState<Poll[]>([]),[creating,setCreating]=useState(false),[question,setQuestion]=useState(''),[options,setOptions]=useState(['','']),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const endpoint='polls'+(chatId?'?chat='+chatId:authorId?'?author='+authorId:'');
 async function load(){const rows=await api<Poll[]>(endpoint);const identity=chatId?await registerDevice(user.id):null;return Promise.all(rows.map(async p=>{try{return {...p,content:identity?await decryptMessage<Content>(chatId!,p.payload as Envelope,identity):p.payload as Content}}catch{return p}}));}
 useEffect(()=>{let live=true,inflight=false;const refresh=async()=>{if(inflight||document.hidden)return;inflight=true;try{const p=await load();if(live){setPolls(p);setError('')}}catch(e){if(live)setError(errorText(e))}finally{inflight=false}};void refresh();const timer=setInterval(refresh,15000);return()=>{live=false;clearInterval(timer)}},[endpoint,user.id]);
 async function create(){setBusy(true);setError('');try{const content={question:question.trim(),options:options.map(v=>v.trim())};let value:Content|Envelope=content;if(chatId){await registerDevice(user.id);const devices=await api<PublicDevice[]>('chats/'+chatId+'/keys');if(!devices.length)throw new Error('Участники ещё не настроили шифрование.');value=await encryptMessage(chatId,content,devices)}await api(endpoint,'POST',{payload:value,optionCount:options.length});setPolls(await load());setQuestion('');setOptions(['','']);setCreating(false)}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 return <section className="polls-section" aria-label="Опросы">{!readOnly&&<button className="secondary" onClick={()=>setCreating(!creating)}>{creating?'Отменить':'Создать опрос'}</button>}{creating&&<form className="poll-editor glass-panel" onSubmit={e=>{e.preventDefault();void create()}}><label>Вопрос<input required maxLength={300} value={question} onChange={e=>setQuestion(e.target.value)}/></label>{options.map((v,i)=><label key={i}>Вариант {i+1}<input required maxLength={150} value={v} onChange={e=>setOptions(options.map((s,n)=>n===i?e.target.value:s))}/></label>)}<div className="extra-actions">{options.length<10&&<button type="button" className="secondary" onClick={()=>setOptions([...options,''])}>Добавить вариант</button>}<button disabled={busy} className="primary">Опубликовать опрос</button></div>{chatId&&<small>Вопрос и варианты зашифрованы. Сервер подсчитывает голоса.</small>}</form>}{error&&<p role="alert" className="error">{error}</p>}{polls.map(p=>{const total=Object.values(p.counts).reduce((a,b)=>a+b,0);return <article className="poll-card glass-panel" key={p.id}><UserName user={p.author}/>{p.content?<><h3>{p.content.question}</h3><div className="poll-options">{p.content.options.map((option,i)=>{const count=p.counts[i]||0,percent=total?Math.round(count/total*100):0;return <button disabled={busy} className="poll-option" aria-pressed={p.choice===i} key={i} onClick={async()=>{setBusy(true);try{await api('polls/'+p.id,'POST',{choice:i});setPolls(await load())}catch(e){setError(errorText(e))}finally{setBusy(false)}}}><span className="poll-fill" style={{width:percent+'%'}}/><span>{p.choice===i?'✓ ':''}{option}</span><b>{percent}%</b></button>})}</div><small>{total} голосов · один вариант · голос можно изменить</small></>:<p>Опрос недоступен на этом устройстве: нет ключа расшифровки.</p>}</article>})}</section>
}
