"use client";
import {builtinLabels} from '@/lib/studio-builtins';
import {useEffect} from 'react';
export function StudioBridge(){useEffect(()=>{
 if(window.parent===window||!new URLSearchParams(location.search).has('studio'))return;
 let mode='select',grid=8,selected:HTMLElement|null=null,drag:{x:number;y:number;left:number;top:number;width:number;height:number;edge:string;rectX:number;rectY:number}|null=null;
 const send=(data:object)=>window.parent.postMessage(data,location.origin),snap=(v:number)=>grid?Math.round(v/grid)*grid:v;
 const outline=document.createElement('div');outline.className='studio-selection-box';outline.dataset.editorChrome='true';document.body.appendChild(outline);
 for(const edge of ['nw','n','ne','e','se','s','sw','w']){const handle=document.createElement('div');handle.dataset.resize=edge;handle.className='studio-resize-handle handle-'+edge;outline.appendChild(handle)}
 const draw=()=>{document.documentElement.style.setProperty('--studio-scroll-x',-scrollX+'px');document.documentElement.style.setProperty('--studio-scroll-y',-scrollY+'px');if(!selected||!selected.isConnected||mode==='browse'){outline.style.display='none';return}const r=selected.getBoundingClientRect();Object.assign(outline.style,{display:'block',left:r.left+'px',top:r.top+'px',width:r.width+'px',height:r.height+'px'})};
 function selector(el:HTMLElement):string{if(el.id&&/^[a-zA-Z][\w-]*$/.test(el.id))return '#'+el.id;const parts:string[]=[];let current:HTMLElement|null=el;while(current&&current!==document.body){if(current.classList.contains('sidebar')){parts.unshift('.sidebar');break}if(current.classList.contains('main-content')){parts.unshift('.main-content'+Array.from(current.classList).filter(c=>c.startsWith('view-')).map(c=>'.'+c).join(''));break}const parent:HTMLElement|null=current.parentElement;if(!parent)break;parts.unshift(current.tagName.toLowerCase()+':nth-child('+(Array.from(parent.children).indexOf(current)+1)+')');current=parent}return parts.join(' > ')}
 function select(el:HTMLElement){selected?.removeAttribute('data-studio-selected');selected=el;el.setAttribute('data-studio-selected','true');const r=el.getBoundingClientRect();send({type:'studio-select',target:selector(el),label:(el.innerText||el.getAttribute('aria-label')||el.tagName).trim().slice(0,100),text:Array.from(el.childNodes).filter(n=>n.nodeType===3).map(n=>n.textContent).join('').trim()||el.querySelector('span')?.textContent||'',width:r.width,height:r.height,actions:el.dataset.studioTab?[{type:'tab',tab:el.dataset.studioTab}]:el.dataset.studioAction?[{type:'builtin',name:el.dataset.studioAction}]:el.getAttribute('aria-label')?.includes('тема')?[{type:'theme',theme:'toggle'}]:el.matches('button,a,summary')?[{type:'control',target:selector(el),label:(el.innerText||el.getAttribute('aria-label')||'Действие кнопки').slice(0,100)}]:[]});draw()}
 const down=(e:PointerEvent)=>{if(mode==='browse'||!(e.target instanceof Element))return;const edge=(e.target as HTMLElement).dataset.resize||'';const el=edge?selected:e.target.closest<HTMLElement>('button,a,summary')||e.target.closest<HTMLElement>('[id^="studio-block-"],button,a,label,h1,h2,h3,p,small,span,input,textarea,section,article,header,aside,main,div');if(!el||el===document.body||el.closest('[data-editor-chrome]'))return;e.preventDefault();e.stopImmediatePropagation();select(el);if(mode==='move'||edge){const xy=getComputedStyle(el).translate.split(' ').map(parseFloat),r=el.getBoundingClientRect();drag={x:e.clientX,y:e.clientY,left:xy[0]||0,top:xy[1]||0,width:r.width,height:r.height,edge,rectX:r.left+scrollX,rectY:r.top+scrollY};el.setPointerCapture(e.pointerId)}};
 const move=(e:PointerEvent)=>{if(!drag||!selected)return;e.preventDefault();const dx=e.clientX-drag.x,dy=e.clientY-drag.y;let x=drag.left,y=drag.top;if(!drag.edge){x+=snap(drag.rectX+dx)-drag.rectX;y+=snap(drag.rectY+dy)-drag.rectY}else{let w=drag.width,h=drag.height;if(drag.edge.includes('e'))w=Math.max(16,snap(drag.width+dx));if(drag.edge.includes('s'))h=Math.max(16,snap(drag.height+dy));if(drag.edge.includes('w')){w=Math.max(16,snap(drag.width-dx));x+=drag.width-w}if(drag.edge.includes('n')){h=Math.max(16,snap(drag.height-dy));y+=drag.height-h}selected.style.setProperty('width',w+'px','important');selected.style.setProperty('height',h+'px','important');selected.style.setProperty('min-width','0','important');selected.style.setProperty('max-width','none','important');selected.style.boxSizing='border-box';selected.style.flexShrink='0'}selected.style.translate=x+'px '+y+'px';draw()};
 const up=()=>{if(drag&&selected){const xy=selected.style.translate.split(' ').map(parseFloat);send({type:'studio-move',target:selector(selected),x:xy[0]||0,y:xy[1]||0,...(drag.edge?{width:parseFloat(selected.style.width),height:parseFloat(selected.style.height)}:{})})}drag=null};
 const click=(e:Event)=>{if(mode!=='browse'){e.preventDefault();e.stopImmediatePropagation()}};
 const dragover=(e:DragEvent)=>{if(e.dataTransfer?.types.includes('application/x-telejka-element')){e.preventDefault();e.dataTransfer.dropEffect='copy'}};
 const drop=(e:DragEvent)=>{const kind=e.dataTransfer?.getData('application/x-telejka-element');if(!['button','panel','text'].includes(kind||''))return;e.preventDefault();e.stopPropagation();send({type:'studio-drop',kind,x:snap(e.clientX+scrollX),y:snap(e.clientY+scrollY)})};
 const receive=(e:MessageEvent)=>{if(e.origin!==location.origin||e.source!==window.parent)return;if(e.data?.type==='studio-mode'){mode=e.data.mode;grid=Number.isFinite(e.data.grid)?e.data.grid:8;document.documentElement.dataset.studioGrid=grid?'on':'off';document.documentElement.dataset.studioMode=mode;document.documentElement.style.setProperty('--studio-grid',grid+'px');draw()}if(e.data?.type==='studio-parent'&&selected?.parentElement)select(selected.parentElement);if(e.data?.type==='studio-focus')requestAnimationFrame(()=>{const el=document.getElementById(e.data.id);if(el){select(el);el.scrollIntoView({block:'nearest'})}})};
 const observer=new MutationObserver(records=>{if(records.some(r=>r.type==='childList'||r.target===selected))requestAnimationFrame(draw)});observer.observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['style']});document.addEventListener('pointerdown',down,true);document.addEventListener('pointermove',move,true);document.addEventListener('pointerup',up,true);document.addEventListener('pointercancel',up,true);document.addEventListener('click',click,true);document.addEventListener('dragover',dragover);document.addEventListener('drop',drop);window.addEventListener('message',receive);window.addEventListener('scroll',draw,true);window.addEventListener('resize',draw);document.documentElement.dataset.studioMode=mode;send({type:'studio-ready'});
 return()=>{observer.disconnect();outline.remove();selected?.removeAttribute('data-studio-selected');delete document.documentElement.dataset.studioMode;document.removeEventListener('pointerdown',down,true);document.removeEventListener('pointermove',move,true);document.removeEventListener('pointerup',up,true);document.removeEventListener('pointercancel',up,true);document.removeEventListener('click',click,true);document.removeEventListener('dragover',dragover);document.removeEventListener('drop',drop);window.removeEventListener('message',receive);window.removeEventListener('scroll',draw,true);window.removeEventListener('resize',draw)};
 },[]);return null}
