"use client";
import {useEffect,useState} from 'react';
import {StudioBridge} from './studio-bridge';
import {createPortal} from 'react-dom';
import {api,errorText} from './shared';
import {emptyStudio,studioSchema,targets,type StudioConfig,type StudioAction} from '@/lib/studio-schema';
const nativeClicks=new WeakSet<HTMLElement>();
function originalClick(el:HTMLElement|null){if(!el){window.dispatchEvent(new CustomEvent('studio-notice',{detail:'Сначала открой раздел, в котором находится это действие.'}));return}nativeClicks.add(el);try{el.click()}finally{nativeClicks.delete(el)}}
async function runActions(actions:StudioAction[]){for(const action of actions){if(action.type==='tab')window.dispatchEvent(new CustomEvent('studio-tab',{detail:action.tab}));if(action.type==='builtin')originalClick(document.querySelector<HTMLElement>('[data-studio-action="'+action.name+'"]'));if(action.type==='control'){try{originalClick(document.querySelector<HTMLElement>(action.target))}catch{}} if(action.type==='notice')window.dispatchEvent(new CustomEvent('studio-notice',{detail:action.text}));if(action.type==='navigate'){window.location.assign(action.url);return}if(action.type==='wait')await new Promise(resolve=>setTimeout(resolve,action.seconds*1000));if(action.type==='theme'){const theme=action.theme==='toggle'?(document.documentElement.dataset.theme==='dark'?'light':'dark'):action.theme;document.documentElement.dataset.theme=theme;localStorage.setItem('telejka-theme',theme)}if(action.type==='scroll')document.getElementById('studio-block-'+action.id)?.scrollIntoView({behavior:'smooth',block:'center'});if(action.type==='text'){const el=document.getElementById('studio-block-'+action.id);if(el){const text=Array.from(el.childNodes).find(n=>n.nodeType===3);if(text)text.textContent=action.text}}if(action.type==='toggle'){const el=document.getElementById('studio-block-'+action.id);if(el)el.style.display=el.style.display==='none'?'':'none'}if(action.type==='visibility'){const el=document.getElementById('studio-block-'+action.id);if(el)el.style.display=action.visible?'':'none';}}}
export function StudioBlocks({blocks}:{blocks:StudioConfig['blocks']}){const [notice,setNotice]=useState('');useEffect(()=>{const show=(e:Event)=>setNotice(String((e as CustomEvent).detail));window.addEventListener('studio-notice',show);return()=>window.removeEventListener('studio-notice',show)},[]);return <div className="studio-blocks">{blocks.map(b=>{const style:React.CSSProperties=b.layout?{position:'absolute',left:b.layout.x,top:b.layout.y,width:b.layout.width,height:b.layout.height,zIndex:b.layout.z??1,margin:0,boxSizing:'border-box',pointerEvents:'auto'}:{};const props={id:'studio-block-'+b.id,style};const element=b.type==='button'?<button {...props} className="secondary" onClick={()=>{void runActions(b.actions||(b.action?[b.action]:[]))}}>{b.text}</button>:b.type==='panel'?<section {...props} className="glass-panel studio-panel">{b.text}</section>:<p {...props}>{b.text}</p>;return b.layout&&typeof document!=='undefined'?createPortal(element,document.body,b.id):<div key={b.id} className="studio-flow-element">{element}</div>})}{notice&&<div role="status" className="glass-panel studio-notice"><p>{notice}</p><button className="secondary" onClick={()=>setNotice('')}>Закрыть</button></div>}</div>}
export function StudioRuntime({configOverride}:{configOverride?:StudioConfig}={}){const [config,setConfig]=useState<StudioConfig>(emptyStudio),[mount,setMount]=useState<Element|null>(null);
 useEffect(()=>{if(configOverride)setConfig(configOverride)},[configOverride]);
 useEffect(()=>{if(location.pathname.startsWith('/admin')||!location.pathname.startsWith('/feed'))return;let live=true;const receive=(event:MessageEvent)=>{if(event.origin===location.origin&&event.source===window.parent&&window.parent!==window&&event.data?.type==='studio-preview'){const parsed=studioSchema.safeParse(event.data.config);if(parsed.success)setConfig(parsed.data)}};window.addEventListener('message',receive);const load=()=>api<{config:StudioConfig}>('studio').then(v=>{if(live){setConfig(studioSchema.parse(v.config));if(window.parent!==window)window.parent.postMessage({type:"studio-ready"},location.origin)}}).catch(()=>{});void load();const timer=setInterval(()=>{if(window.parent===window)void load()},30000);return()=>{live=false;clearInterval(timer);window.removeEventListener('message',receive)}},[]);
 useEffect(()=>{if(location.pathname.startsWith('/admin'))return;const listeners=new Map<HTMLElement,(e:Event)=>void>();const originals=new Map<HTMLElement,{css:string;text:Text|null;value:string}>();let queued=false;
 const apply=()=>{queued=false;setMount(document.querySelector('.main-content'));for(const o of config.overrides){document.querySelectorAll<HTMLElement>(o.target).forEach(el=>{if(el.closest("#telejka-mobile-navigation"))return;if(!originals.has(el)){const label=el.matches('button,a')?(el.querySelector('span')||el):el;const text=label?Array.from(label.childNodes).find(n=>n.nodeType===Node.TEXT_NODE&&n.textContent?.trim()) as Text|undefined:null;originals.set(el,{css:el.getAttribute('style')||'',text:text||null,value:text?.textContent||''})}el.style.setProperty('translate',`${o.x}px ${o.y}px`);el.style.setProperty('order',String(o.order));if(o.width!==undefined){el.style.setProperty('width',o.width+'px','important');el.style.setProperty('min-width','0','important');el.style.setProperty('max-width','none','important');el.style.boxSizing='border-box';el.style.flexShrink='0'}if(o.height!==undefined)el.style.setProperty('height',o.height+'px','important');if(o.z!==undefined){el.style.zIndex=String(o.z);if(getComputedStyle(el).position==='static')el.style.position='relative'}if(o.hidden)el.style.setProperty('display','none','important');if(o.actions!==undefined&&!listeners.has(el)){const click=(e:Event)=>{if(nativeClicks.has(el))return;e.preventDefault();e.stopPropagation();void runActions(o.actions!)};el.addEventListener('click',click,true);listeners.set(el,click)}const saved=originals.get(el)!;if(o.text!==undefined&&saved.text&&saved.text.textContent!==o.text)saved.text.textContent=o.text})}};
 apply();const observer=new MutationObserver(()=>{if(!queued){queued=true;queueMicrotask(apply)}});observer.observe(document.body,{childList:true,subtree:true});return()=>{observer.disconnect();for(const [el,click]of listeners)el.removeEventListener('click',click,true);for(const [el,saved]of originals){el.setAttribute('style',saved.css);if(saved.text)saved.text.textContent=saved.value}}},[config]);
 return <><StudioBridge/>{mount?createPortal(<StudioBlocks blocks={config.blocks}/>,mount):null}</>;
}
export function CustomStudioPage({slug}:{slug:string}){const [config,setConfig]=useState<StudioConfig>(),[error,setError]=useState('');useEffect(()=>{let live=true;const receive=(e:MessageEvent)=>{if(e.origin===location.origin&&e.source===window.parent&&window.parent!==window&&e.data?.type==='studio-preview'){const parsed=studioSchema.safeParse(e.data.config);if(parsed.success)setConfig(parsed.data)}};window.addEventListener('message',receive);api<{config:StudioConfig}>('studio').then(v=>{if(live){setConfig(v.config);if(window.parent!==window)window.parent.postMessage({type:'studio-ready'},location.origin)}}).catch(e=>setError(errorText(e)));return()=>{live=false;window.removeEventListener('message',receive)}},[]);const page=config?.pages.find(p=>p.slug===slug);return <main className="studio-page glass-panel"><StudioRuntime configOverride={config}/><a href="/feed">← TELEJKA</a>{error?<p role="alert">{error}</p>:!config?<p>Загрузка…</p>:page?<><h1>{page.title}</h1><StudioBlocks blocks={page.blocks}/></>:<h1>Страница не найдена</h1>}</main>}
export {StudioAdmin} from "./visual-studio";
