"use client";
import {useEffect,useRef,useState} from 'react';
import {Mic,Square,X} from 'lucide-react';
export function VoiceRecorder({onFile,disabled}:{onFile:(file:File)=>void;disabled:boolean}){
 const [recording,setRecording]=useState(false),[seconds,setSeconds]=useState(0),[error,setError]=useState('');const mounted=useRef(true),pending=useRef(false);const recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),chunks=useRef<Blob[]>([]),cancelled=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;cancelled.current=true;recorder.current?.state==='recording'&&recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop())}},[]);
 useEffect(()=>{if(!recording)return;const timer=setInterval(()=>setSeconds(s=>{if(s>=299)recorder.current?.stop();return s+1}),1000);return()=>clearInterval(timer)},[recording]);
 async function start(){if(pending.current||recording)return;pending.current=true;try{setError('');if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined')throw new Error('Запись голоса не поддерживается этим браузером.');const audio=await navigator.mediaDevices.getUserMedia({audio:true});if(!mounted.current){audio.getTracks().forEach(t=>t.stop());return}stream.current=audio;const mime=['audio/webm;codecs=opus','audio/mp4','audio/webm'].find(t=>MediaRecorder.isTypeSupported(t));const r=new MediaRecorder(audio,mime?{mimeType:mime}:undefined);recorder.current=r;chunks.current=[];cancelled.current=false;r.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};r.onstop=()=>{audio.getTracks().forEach(t=>t.stop());if(mounted.current)setRecording(false);if(cancelled.current||!mounted.current)return;const type=r.mimeType.split(';')[0],blob=new Blob(chunks.current,{type});if(blob.size>25*1024*1024){setError('Запись слишком большая.');return}if(blob.size)onFile(new File([blob],'Голосовое-'+Date.now()+(type.includes('mp4')?'.m4a':'.webm'),{type}));};r.start(1000);setSeconds(0);setRecording(true)}catch(e){stream.current?.getTracks().forEach(t=>t.stop());setError(e instanceof Error?e.message:'Не удалось включить микрофон.')}finally{pending.current=false}}
 return <div className="voice-recorder">{recording?<><span role="status">● {Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</span><button type="button" aria-label="Завершить запись" onClick={()=>recorder.current?.stop()}><Square size={18}/></button><button type="button" aria-label="Отменить запись" onClick={()=>{cancelled.current=true;recorder.current?.stop()}}><X size={18}/></button></>:<button type="button" className="icon-button" disabled={disabled} aria-label="Записать голосовое" onClick={start}><Mic size={20}/></button>}{error&&<small role="alert">{error}</small>}</div>
}
